/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Represents the AccessSections that can be passed via the `x-access-section` header for API requests.
 */
export enum AccessSections {
  DESCRIBE_CONTACT = 'DESCRIBE_CONTACT',
  DESCRIBE_CONTACT_FLOW = 'DESCRIBE_CONTACT_FLOW',
  GET_AUTHORIZED_WIDGETS_FOR_USER = 'GET_AUTHORIZED_WIDGETS_FOR_USER',
  GET_CONTACT = 'GET_CONTACT',
  LIST_INTEGRATION_ASSOCIATIONS = 'LIST_INTEGRATION_ASSOCIATIONS',
  WISDOM = 'WISDOM',
  WISDOM_GET_CONTENT = 'WISDOM_GET_CONTENT',
  WISDOM_GET_NEXT_MESSAGE = 'WISDOM_GET_NEXT_MESSAGE',
  WISDOM_GET_RECOMMENDATIONS = 'WISDOM_GET_RECOMMENDATIONS',
  WISDOM_GET_SESSION = 'WISDOM_GET_SESSION',
  WISDOM_LIST_CONTENT_ASSOCIATIONS = 'WISDOM_LIST_CONTENT_ASSOCIATIONS',
  WISDOM_NOTIFIY_RECOMMENDATIONS_RECEIVED = 'WISDOM_NOTIFIY_RECOMMENDATIONS_RECEIVED',
  WISDOM_PUT_FEEDBACK = 'WISDOM_PUT_FEEDBACK',
  WISDOM_QUERY_ASSISTANT = 'WISDOM_QUERY_ASSISTANT',
  WISDOM_SEARCH_SESSIONS = 'WISDOM_SEARCH_SESSIONS',
  WISDOM_SEND_MESSAGE = 'WISDOM_SEND_MESSAGE',
}
